#!/usr/bin/env python3
import requests


r = requests.get('https://www.bing.com/HPImageArchive.aspx?format=xml&idx=0&n=1&mkt=sv-se')
text = r.text
text = text.split('<url>')[1]
text = text.split('</url>')[0]

url = 'www.bing.com' + text
