#!/usr/bin/env bash
time=/tmp/$(date +%F.%T).png
import -silent $time

if [[ -f "$time" ]]; then
  rotation_needed="$(identify -format '%[fx:w>h]' "$time" 2>/dev/null || true)"
  if [[ -n "$rotation_needed" ]] && (( rotation_needed )); then
    magick convert "$time" -rotate 90 "$time"
  fi
fi

#/home/kentagent/.cargo/bin/kvitto -i $time -o /tmp/kvitto
#echo "HELLO"
scp "$time" "pi@ssh.antonlinder.xyz:/tmp/kvittofil.png"
ssh pi@ssh.antonlinder.xyz "kvitto -i /tmp/kvittofil.png"
