#!/usr/bin/env bash
time=/tmp/$(date +%F.%T).png
import $time

(( $(identify -format '%w > %h' "$time") )) && magick convert "$time" -rotate 90 $time; 


#/home/kentagent/.cargo/bin/kvitto -i $time -o /tmp/kvitto
#echo "HELLO"
scp "$time" pi@ssh.antonlinder.xyz:/tmp/kvittofil.png
echo "TRANSFER"
ssh pi@ssh.antonlinder.xyz " kvitto -i /tmp/kvittofil.png" 
echo "Printed"
