#!/bin/sh

#Clear the download folder on each boot. 
rm -rf /home/kentagent/Downloads/*

#Download picture of the day
wget $(exec /home/kentagent/nixos/helper-scripts/bingimage) -O /home/kentagent/Downloads/img.png
feh --bg-center /home/kentagent/Downloads/img.png

#Start the notification deamon
dunst &

notify-send "Startup done"
